version: '2'

services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    network_mode: host
    depends_on:
      - ganache-cli
      - ipfs
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    network_mode: host
    depends_on:
      - server
      - ganache-cli
      - ipfs
  ganache-cli:
    ports:
        - "8545:8545"
    network_mode: host
    image: 'trufflesuite/ganache-cli:latest'
  ipfs:
    image: jbenet/go-ipfs
    network_mode: host
    ports: 
      - "5001:5001"