version: '2'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017