export const GET_TOTAL_TOKENS = 'GET_TOTAL_TOKENS'
export const TOTAL_TOKENS_RECEIVED = 'TOTAL_TOKENS_RECEIVED'
export const GET_USER_TOKENS = 'GET_USER_TOKENS'
export const USER_TOKENS_RECEIVED = 'USER_TOKENS_RECEIVED'
