export const TRANSACTION_PENDING = 'TRANSACTION_PENDING'
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS'
export const TRANSACTION_FAILURE = 'TRANSACTION_FAILURE'
export const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION'
